Aggiunto database engine sqlite
Argo-swe/ChatSQL pull request #18
Opened 2024-05-29 18:42 UTC by stoccotommaso02

[ARGO-56]
Pingo @mzecchinato che può dare del feedback sulla struttura, vista anche la configurazione di un servizio su Compose.
La struttura che vogliamo utilizzare per la condivisione delle tabelle si può ovviamente modificare, se vediamo che il solo `schema.sql` risulta inadeguato. Il README aggiunto inoltre è una guida pratica interna, valutate se mantenerlo o disaccoppiarlo

2024-05-29 18:43 UTC, Rikicavaz77 commented
@stoccotommaso02 metto anche Mattia come verificatore

2024-05-29 18:50 UTC, stoccotommaso02 commented
Un problema che si potrà porre in futuro tra l'altro è la persistenza della relazione dizionari dati in json-entry nel db, soprattutto se ne caricheremo diversi, però penso sia qualcosa che un workflow di Github potrà risolvere se non lo si voglia fare direttamente a mano

2024-05-30 10:00 UTC, stoccotommaso02 commented
Con Mattia abbiamo stabilito che la gestione di sqlite tramite un container a parte è superflua e sarà aggiunto a un'immagine che comprenda tutti gli step del workflow, ho dunque rimosso i file e i riferimenti al container e modificato la struttura della directory poiché non è necessario considerare i volumi del container.

2024-05-30 11:51 UTC, Rikicavaz77 requested changes

2024-05-30 11:51 UTC, Rikicavaz77 commented on db/schema.sql
> +  password TEXT NUT NULL
```suggestion
  password TEXT NOT NULL
```

2024-05-30 13:38 UTC, Rikicavaz77 approved these changes
LGTM

2024-05-30 13:38 UTC, merged