Refactoring Index Manager
Argo-swe/ChatSQL pull request #19
Opened 2024-05-30 16:06 UTC by Rikicavaz77

2024-05-30 16:09 UTC, Rikicavaz77 commented
Il file `two_indexes.py` non richiede verifica, in quanto mantenuto solamente come spazio di ricerca.

2024-05-31 13:19 UTC, CristoMarco requested changes
Sembra andare tutto a parte quei due accorgimenti

2024-05-31 13:19 UTC, CristoMarco commented on App/index_manager.py
> +    def __getTuples(self, user_request):
Per i metodi che non sono ridefinizione di metodi standard (tipo string o init) ma che sono di appoggio ad altri metodi all'interno della classe, penso che ci vada un '_' prima del metodo anzi che '__'

2024-05-31 13:19 UTC, CristoMarco commented on App/index_manager.py
> +    def __getRelevantTuples(self, tuples):
Anche qui come per riga 33

2024-05-31 20:24 UTC, CristoMarco approved these changes, later dismissed

2024-06-02 13:06 UTC, Rikicavaz77 commented
@CristoMarco la classa Multi Extractor l'ho trasformata in un contenitore di metodi, poi se necessario si potrà reimplementarla come classe.

2024-06-02 13:07 UTC, Rikicavaz77 commented
Ho caricato anche la cartella degli Indici, può tornare utile?

2024-06-02 20:11 UTC, Rikicavaz77 commented
@CristoMarco dopo aver fatto la verifica, aspetta a fare il merge, così carico delle piccole modifiche per allinearmi alla struttura della repo pensata in ARGO-67-Caricamento-del-dizionario-dati.

2024-06-02 20:14 UTC, Rikicavaz77 commented
Sotto-task:

- [ ] Aggiungere notazione class in `schema_multi_extractor.py`;
- [ ] Integrare `schema_multi_extractor.py` con `utils.py` per evitare ridondanze;
- [ ] Allineare la struttura della repo con il develop.

2024-06-03 08:36 UTC, Rikicavaz77 commented
@CristoMarco ho dovuto costruire il branch sopra quello di Mattia, quindi alcune cose sono ridondanti. Puoi anche evitare la verifica completa dei duplicati di https://github.com/Argo-swe/ChatSQL/pull/20, e darci solo un'occhiata veloce.

2024-06-03 08:37 UTC, Rikicavaz77 commented
Da valutare @CristoMarco :

- [ ] Spostamento della cartella Indici in backend (opportuno);
- [ ] Spostamento della cartella DizionarioDati in backend.

2024-06-03 09:12 UTC, CristoMarco commented
Ho decommentato il main dell'index manager per testarlo, ma mi dà questo errore:
![image](https://github.com/Argo-swe/ChatSQL/assets/162626105/bbf5c40c-4e17-49e9-8b61-c14e22755749)

2024-06-03 09:13 UTC, Rikicavaz77 commented
> Ho decommentato il main dell'index manager per testarlo, ma mi dà questo errore:

devi mettere `backend/index_manager` per testarlo singolarmente, a partire da App.

2024-06-03 10:10 UTC, CristoMarco approved these changes
Ora funziona.

2024-06-03 10:11 UTC, merged