Feature login
Argo-swe/ChatSQL pull request #40
Opened 2024-06-20 08:28 UTC by stoccotommaso02

[ARGO-104]
- Aggiunti modelli di DTO per autenticazione
- Aggiunta route per login con lettura da database
- Aggiunte dipendenze alle route per Tecnico (create, update, delete di dizionari)

Elementi mancanti:
- Una gestione dei segreti per chiave e algoritmo di encoding del JWT (si può considerare anche dopo il PoC)
- Route per logout: revocare JWT è piuttosto macchinoso, penso sia più opportuna una soluzione che appende a una route "vuota" una logica frontend per eliminare il token
- Connessione alla componente di login frontend e meccanismo di passaggio del JWT alle richieste da Tecnico (lato frontend)

[ARGO-104]: https://argo-swe-2.atlassian.net/browse/ARGO-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-20 19:17 UTC, mzecchinato requested changes
Ho aggiunto proprio due spazi da sistemare

2024-06-20 19:17 UTC, mzecchinato commented on backend/app/app.py
> +from routes.login_api import router as login_router
```suggestion
from routes.login_api import router as login_router

```

2024-06-20 19:17 UTC, mzecchinato commented on backend/app/models/login_dto.py
> +    username : str
```suggestion
    username: str
```

2024-06-20 19:18 UTC, mzecchinato commented
la route per il JWT non dovrebbe servire, facciamo tutto lato FE eliminando dalla localstorage il token salvato

2024-06-20 19:27 UTC, mzecchinato commented
mi riesci a dare i passaggi per impostare il DB?

2024-06-23 17:38 UTC, Rikicavaz77 commented
@stoccotommaso02 @mzecchinato qui manca qualcosa?

2024-06-23 18:11 UTC, mzecchinato commented
> @stoccotommaso02 @mzecchinato qui manca qualcosa?

si c'è la struttura di login funzionante con la richiesta al BE, ma va fatto il merge delle funzionalità con la PR #44 che ha nuove funzionalità relative al DB, ma quando abbiamo tutto il codice in develop apriamo un PR di allieamento funzionalità se no abbiamo tutto troppo sparso

2024-06-23 18:11 UTC, mzecchinato approved these changes
LGTM

2024-06-24 06:18 UTC, Rikicavaz77 commented
@mzecchinato c'è un piccolo conflitto in `Login.vue`. Si può risolvere anche direttamente dall'interfaccia di GitHub.

2024-06-24 06:43 UTC, merged