Prototipo dizionario dati [in inglese]
Argo-swe/ChatSQL pull request #5
Opened 2024-05-10 17:39 UTC by Rikicavaz77

2024-05-14 13:33 UTC, CristoMarco requested changes
Buono. Si potrebbe anche aggiungere il dizionario dati in italiano per testarlo con BERTino

2024-05-14 13:33 UTC, CristoMarco commented on App/main.py
> +""")
Direi che si può aggiungere il primo test di inserimento query dato che lo abbiamo pronto

2024-05-14 13:33 UTC, CristoMarco commented on DizionarioDati/orders.json
Buono

2024-05-17 14:13 UTC, CristoMarco approved these changes
Il codice è adatto

2024-05-17 14:13 UTC, merged

2024-05-17 18:20 UTC, Rikicavaz77 commented
[ARGO-33] Iniziato anche lo sviluppo della web app