Update componenti
Argo-swe/ChatSQL pull request #59
Opened 2024-07-31 17:15 UTC by Rikicavaz77

2024-08-02 14:12 UTC, Rikicavaz77 commented
- [ ] L'interfaccia va spostata in `ChatView`, perché  è abbastanza inutile in `ChatDeleteBtn`. L'ho messa lì come esempio di convenzione sui commenti delle interfacce.

2024-08-03 14:21 UTC, Rikicavaz77 commented
La mia idea sarebbe questa (può anche essere scartata):

Aggiungere un file `wrapper` per definizioni di tipi e interfacce.

- Qui si definiscono i tipi, a partire da openapi, in modo da facilitare l'import. Userei type in quando sono lo specchio dei dati nel back-end, quindi non dovrebbero essere soggetti a espansione.

![image](https://github.com/user-attachments/assets/9566bbca-ba8c-41d0-ba3f-4b10cfe68ded)

- Qui invece si definiscono le interfacce specifiche del front-end. 

![image](https://github.com/user-attachments/assets/ba1fe4a2-00fb-4ca0-a308-2196ed50456f)

2024-08-03 14:24 UTC, Rikicavaz77 commented
In caso rimuovo i types da wrapper e tengo solo un file per accorpare le interfacce.

2024-08-03 18:47 UTC, Rikicavaz77 commented
- Ho pushato anche altre modifiche. Alcuni sono fix su consigli del plugin di typescript (da controllare bene, che potrei aver perso qualcosa per strada); altre cose sono rivisitazioni dei metodi per abbassare la complessità ciclomatica. Ho usato l'estensione SonarLint per VsCode. Non siamo messi male come complessità dei metodi (da sistemare qualcosa in ChatView e DictionariesList).

2024-08-03 20:38 UTC, mzecchinato requested changes
ottimo refactoring

2024-08-03 20:38 UTC, mzecchinato commented on frontend/src/components/AppLogo.vue
> +  setup(props) {
```suggestion
  setup() {
```
non usata per rimuovere il warning

2024-08-03 20:38 UTC, mzecchinato commented on frontend/src/components/DictPreview.vue
> +  setup(props) {
```suggestion
  setup() {
```
non usata per rimuovere il warning

2024-08-03 20:38 UTC, mzecchinato commented on frontend/src/views/ChatView.vue
>  // Variabile per controllare la visibilità dei dettagli
```suggestion
// Variable to handle details visibility
```

2024-08-03 20:38 UTC, mzecchinato commented on frontend/src/views/ChatView.vue
>  // Ritorno il nome del dizionario dati selezionato
```suggestion
// Return selected dictionary name
```

2024-08-03 20:38 UTC, mzecchinato commented on frontend/src/views/ChatView.vue
> +import type { DictionaryPreview, MessageWrapper } from '@/types/wrapper';
```suggestion
import type { DictionaryPreview, MessageWrapper } from '@/types/wrapper';
import type { Components } from '@/types/openapi';
```

2024-08-03 20:38 UTC, mzecchinato commented on frontend/src/views/ChatView.vue
>  const dictionaries = ref();
```suggestion
const dictionaries = ref<Components.Schemas.DictionaryDto[]>();
```
se possibile evitiamo l'utilizzo impicito o esplicito di any

2024-08-03 20:38 UTC, mzecchinato commented on frontend/src/views/ChatView.vue
> +  const dict = dictionaries.value?.find((dict: any) => dict.id === id);
```suggestion
  const dict = dictionaries.value?.find((dict: Components.Schemas.DictionaryDto) => dict.id === id);
```

2024-08-03 20:38 UTC, mzecchinato commented on frontend/src/views/AppLayout.vue
> +const outsideClickListener: Ref<((event: any) => void) | null> = ref(null);
```suggestion
const outsideClickListener: Ref<((event: MouseEvent) => void) | null> = ref(null);
```

2024-08-03 20:38 UTC, mzecchinato commented on frontend/src/views/AppLayout.vue
> +    outsideClickListener.value = (event: any) => {
```suggestion
    outsideClickListener.value = (event: MouseEvent) => {
```

2024-08-03 20:38 UTC, mzecchinato commented on frontend/src/views/AppLayout.vue
> +const isOutsideClicked = (event: any): boolean => {
```suggestion
const isOutsideClicked = (event: MouseEvent): boolean => {
```

2024-08-03 20:38 UTC, mzecchinato commented on frontend/src/views/AppLayout.vue
> +const checkNodeRelation = (element: Element | null, target: any): boolean => {
```suggestion
const checkNodeRelation = (element: Element | null, target: Node | null): boolean => {
```

2024-08-03 20:38 UTC, mzecchinato commented on frontend/src/composables/layout.ts
> +  const setActiveMenuItem = (item: any) => {
qui lascia stare 'any' perchè è un casino a cascata con i campi "compute" in caso faremo a tempo perso

2024-08-04 08:11 UTC, Rikicavaz77 commented
@mzecchinato Il base branch di questa pull request è **frontend**. Però, dato che è stato modificato `requirements`, direi che una volta chiusa la pull request, potremmo fare anche un merge sul **develop**.

2024-08-04 08:24 UTC, mzecchinato approved these changes
LGTM

Si ci sta anche perchè avendo modifiato parecchio la struttura se poi qualcuno ci mette mano in parallelo è complicato il merge

2024-08-04 08:26 UTC, merged