Benchmark modelli
Argo-swe/ChatSQL pull request #6
Opened 2024-05-15 22:09 UTC by Rikicavaz77

2024-05-15 22:24 UTC, Rikicavaz77 commented
@CristoMarco @RaulPianon ho creato una directory che possiamo usare per portare avanti i test dei modelli e della ricerca semantica

2024-05-16 15:06 UTC, RaulPianon commented
[ARGO-48]

2024-05-17 14:20 UTC, CristoMarco requested changes
Se provo a lanciarlo ottengo il seguente errore:

![image](https://github.com/Argo-swe/ChatSQL/assets/162626105/fc99795b-ae11-4707-b6e9-d571ee4e70c8)

2024-05-17 14:28 UTC, CristoMarco approved these changes
Ora è sistemato

2024-05-17 14:28 UTC, merged