Allineamento frontend con il develop
Argo-swe/ChatSQL pull request #63
Opened 2024-08-04 08:27 UTC by Rikicavaz77

2024-08-04 08:39 UTC, mzecchinato commented
non ho capito a cosa serve il branch `frontend`

2024-08-04 08:42 UTC, Rikicavaz77 commented
> non ho capito a cosa serve il branch `frontend`

Serve come backup diciamo, in modo che l'applicazione continui a funzionare anche se magari nel back-end facciamo modifiche agli endpoint.

2024-08-04 08:44 UTC, mzecchinato requested changes
il comportamento in grandi schermi è voluto con la chat a larghezza non 100%
![image](https://github.com/user-attachments/assets/f6d8acd7-f7ee-4936-8e8e-7ac13cdfdd1a)

2024-08-04 08:44 UTC, mzecchinato commented on frontend/src/views/ChatView.vue
> +import type { Components } from '@/types/openapi';
la riga è duplicata

Non so perchè non mi fa piiù fare i suggerimenti

2024-08-04 08:46 UTC, mzecchinato commented
> > non ho capito a cosa serve il branch `frontend`
> 
> Serve come backup diciamo, in modo che l'applicazione continui a funzionare anche se magari nel back-end facciamo modifiche agli endpoint. Poi potrà essere rimosso ovviamente.

direi però di portarlo in develop con queste modifiche, qui possiamo tenerlo attivo

2024-08-04 08:46 UTC, Rikicavaz77 commented
> il comportamento in grandi schermi è voluto con la chat a larghezza non 100%

Forse sì, devo chiedere a Sebastiano. In caso contrario, il fix dovrebbe essere semplice.

2024-08-04 08:46 UTC, Rikicavaz77 commented
> direi però di portarlo in develop con queste modifiche, qui possiamo tenerlo attivo

Sì.

2024-08-04 08:47 UTC, Rikicavaz77 commented on frontend/src/views/ChatView.vue
> +import type { Components } from '@/types/openapi';
Strano

2024-08-04 08:50 UTC, Rikicavaz77 commented
Per me ci sta comunque bloccare la larghezza della chat, perché è simile a ChatGPT come comportamento.

2024-08-05 06:36 UTC, mzecchinato commented
LGTM

(non approvo per tenere il blocco della PR)

2024-08-05 06:46 UTC, Rikicavaz77 commented
> (non approvo per tenere il blocco della PR)

Quindi dici di chiudere la PR quando tutto il front-end è a posto? Però così il `requirements` rimane indietro?

2024-08-05 06:52 UTC, mzecchinato commented
> > (non approvo per tenere il blocco della PR)
> 
> Quindi dici di chiudere la PR quando tutto il front-end è a posto? Però così il `requirements` rimane indietro?

No no io sarei più per chiudere a piccoli passi e poi aprirne di nuove

2024-08-05 06:53 UTC, Rikicavaz77 commented
> > > (non approvo per tenere il blocco della PR)
> > 
> > 
> > Quindi dici di chiudere la PR quando tutto il front-end è a posto? Però così il `requirements` rimane indietro?
> 
> No no io sarei più per chiudere a piccoli passi e poi aprirne di nuove

Allora in realtà questa potrebbe anche essere chiusa volendo.

2024-08-05 06:54 UTC, mzecchinato approved these changes

2024-08-05 06:55 UTC, merged