Test FE AppLogo
Argo-swe/ChatSQL pull request #78
Opened 2024-08-14 08:53 UTC by LewentalDigital

2024-08-14 08:57 UTC, Rikicavaz77 commented
Lascio qui un errore che ho riscontrato:

- Testando `ChatDeleteBtn`, dà problemi perché non trova la funzione `t` di traduzione. Inoltre, dà problemi quando deve trovare componenti di `PrimeVue`.

2024-08-14 09:04 UTC, LewentalDigital commented
> Lascio qui un errore che ho riscontrato:
> 
> * Testando `ChatDeleteBtn`, dà problemi perché non trova la funzione `t` di traduzione. Inoltre, dà problemi quando deve trovare componenti di `PrimeVue`.

Ho visto, credo che sia necessario importare e configurare **vue-i18n** in cypress

Comunque non e' un problema per questo test

2024-08-14 09:06 UTC, Rikicavaz77 commented
> > Lascio qui un errore che ho riscontrato:
> > 
> > * Testando `ChatDeleteBtn`, dà problemi perché non trova la funzione `t` di traduzione. Inoltre, dà problemi quando deve trovare componenti di `PrimeVue`.
> 
> Ho visto, credo che sia necessario importare e configurare **vue-i18n** in cypress
> 
> Comunque non e' un problema per questo test

No infatti, dà errore solo nei componenti in cui usiamo la funzione t.

2024-08-15 07:15 UTC, Rikicavaz77 requested changes

2024-08-15 07:15 UTC, Rikicavaz77 commented on frontend/tests/component/AppLogo.cy.ts
> +        propsData: {
```suggestion
        props: {
```

2024-08-15 07:15 UTC, Rikicavaz77 commented on frontend/tests/component/AppLogo.cy.ts
> +        propsData: {
propsData dovrebbe essere la sintassi di Vue 2.

2024-08-15 09:01 UTC, Rikicavaz77 approved these changes
LGTM

2024-08-15 09:01 UTC, merged