Unit test per txtai_debug_manager_adapter
Argo-swe/ChatSQL pull request #86
Opened 2024-08-17 15:30 UTC by CristoMarco

Lanciare da `backend/app` con `pytest tests/adapter/outcoming/embeddings/txtai/test_txtai_debug_manager_adapter.py `

2024-08-17 15:32 UTC, CristoMarco commented
Prima riuscivo a lanciarlo senza problemi.
Adesso, dopo aver creato ed eliminato un paio di file per altri test, non riesco più a farlo partire nonostante sia rimasto intoccato e usi lo stesso comando di prima.
Vedete se è un mio problema locale o se sto confondendo qualcosa.

2024-08-17 17:04 UTC, Rikicavaz77 commented
Comunque tutti i test dovrebbero andare lanciando solamente pytest senza parametri aggiuntivi.

2024-08-18 09:28 UTC, Rikicavaz77 requested changes
- Semplificare la struttura della cartella `tests` (l'import è corretto);
- Aggiungere `pytest-mock` ai `requirements`.

2024-08-18 14:09 UTC, Rikicavaz77 approved these changes
LGTM

2024-08-18 14:58 UTC, closed without merging